# Generated by Django 3.1.7 on 2021-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210508_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parceiros',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
