# Generated by Django 3.1.7 on 2021-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210708_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=70, unique=True),
        ),
    ]
